### ISSUE TITLE
MER

### ISSUE THREAD

**Issue by guiimarques18** [wesleywrl/TACS-ES-2020-2-FastSell#3]
Não há o MER no https://github.com/wesleywrl/TACS-ES-2020-2-FastSell/tree/main/2.Design/2.3.PDA

**Comment by wesleywrl** [comment]
Professor o MER está na
https://github.com/wesleywrl/TACS-ES-2020-2-FastSell/blob/main/2.Design/2.1.EA/MER.pdf

Em qui., 27 de mai. de 2021 às 16:27, Guilherme Marques <
***@***.***> escreveu:
